= eedemo-xa

This uses JPA to commit a distributed transaction
into two databases, customer and orders, as part of
a single XA transaction. Or so we hope.

Anything involving Java and multi-phase commit absolutely
requires a full Java EE server (such as WildFly), not just Tomcat or Jetty.
(At present TomEE cannot be used because its makers refuse to move up to Java EE 7);

It is set up for the PostgreSQL database and the WildFly server.
*Do not ask me for help moving it to other DB or server products*; 
I charge US$100.00 to ignore each such request, and your sending it constitutes
acceptance of this price.
Well, seriously folks, that's why it's open source: so you can change it yourself.
Please clone the GitHub repo and send a pull request when it's fully working
on your new DB or server.

== Prerequisites:

You must have the following:

. Java 7 or 8;
. http://wildfly.org/[WildFly 8.2] or later Java app server, up and running;
  (potentially other Java EE 7 app servers could be used, if *you* can make it work;
. http://postgresql.org[PostgreSQL], the best relational database;
. PostgreSQL JDBC driver (see postgresql.org for versions);
. http://maven.apache.org[Maven];
. Whatever I've forgotten.

== Setup 

You do have to do a bit of setup to make this thing work!

=== Create the databases

This is for PostgreSQL; for others you can vary these appropriately.

This assumes you have PostgreSQL already running on your computer and configured as a "module"
in the WildFly server.

Since the point of this app is to demonstrate an XA commit, you have to tell PostgreSQL to allow 
"prepared transactions". Try setting

max_prepared_transactions = 20

in _postgres.conf_ (wherever that is on your system; to give you a couple of data points,
on OS X it is /Users/postgres/data/postgresql.conf and on OpenBSD it is 
/var/postgresql/data/postgresql.conf ).

You have to restart (nor reload) the server if you change this file.

Now the actual database creation:

----
$ psql <<!xa
create role xademo login password 'ex eh demo?';
create database xademo_customers owner xademo;
create database xademo_orders owner xademo;
!xa
----

=== Add Datasources in Wildfly standalone.xml:

This is for JBoss WildFly 8; for others you can vary these appropriately.
For postgresql, make sure you use the xa-datasource, not the plain datasource.

----
				<!-- Only for eedemo-xa -->
                <xa-datasource jndi-name="java:jboss/datasources/customersDataSource" pool-name="customersDS" enabled="true">
                    <xa-datasource-property name="ServerName">localhost</xa-datasource-property>
                    <xa-datasource-property name="PortNumber">5432</xa-datasource-property>
                    <xa-datasource-property name="DatabaseName">xademo_customers</xa-datasource-property>
                    <driver>postgresql</driver>
                    <security>
                        <user-name>xademo</user-name>
                        <password>ex eh demo?</password>
                    </security>
                    <validation>
                        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
                        <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
                    </validation>
                </xa-datasource>

				<!-- Only for eedemo-xa -->
                <xa-datasource jndi-name="java:jboss/datasources/ordersDataSource" pool-name="ordersDS" enabled="true">
                    <xa-datasource-property name="ServerName"> localhost </xa-datasource-property>
                    <xa-datasource-property name="PortNumber"> 5432 </xa-datasource-property>
                    <xa-datasource-property name="DatabaseName"> xademo_orders </xa-datasource-property>
                    <driver>postgresql</driver>
                    <security>
                        <user-name>xademo</user-name>
                        <password>ex eh demo?</password>
                    </security>
                    <validation>
                        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"/>
                        <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"/>
                    </validation>
                </xa-datasource>
----

You might have to list the database driver as well, if it's not already there:

----
                <drivers>
                    <driver name="postgresql" module="org.postgresql">
                        <xa-datasource-class>org.postgresql.xa.PGXADataSource</xa-datasource-class>
                    </driver>
					...
                </drivers>
----

=== Restart WildFly

Use your system's scripts or $WF_HOME/bin/standalone.sh

=== Deploy the app

$ cd eedemo-xa
$ mvn wildfly:deploy

=== Run it

Finally, you can visit http://localhost:8080/eedemo-xa and work through both buttons.
Each should return a one-line summary, not a stack trace!

=== Verify

You want to verify outside of the app:

----
$ psql -d xademo_customers -c 'select * from customer;'
# You should see one customer with non-zero orders:
 id | name  | numberoforders | version 
----+-------+----------------+---------
  1 | Alpha |              2 |       2
(1 row)

$ psql -d xademo_orders -c 'select * from orders;'
# You should see order(s) with quantity 42, none with quantity 86:
 id |    date    | quantity | version 
----+------------+----------+---------
 -1 |            |        0 |     100
  1 | 2015-06-24 |       42 |       0
  2 | 2015-06-24 |       42 |       0
(3 rows)
----

The order with id of -1 is a placeholder put there during app startup, and can be ignored
(or even deleted if you like).

=== Clean up

If you want to free up the resources from the demo:

. cd eedemo-xa; mvn wildfly:undeploy
. Stop Wildfly
. psql -c 'drop database xademo_customers'
. psql -c 'drop database xademo_orders'
. Remove the two datasource definitions from Wildfly standalone.xml
. Restart Wildfly

Hope you enjoyed this project!

== TODO

Things to do to improve it:

. The Order should have an @ManyToOne to Customer, adding customer_id to the orders table.
. Delete the "done" page and move the messages into the main page (simple).
. The Reporting programs in src/main/java/admin have not worked in a long time,
since the persistence.xml file is set up for JTA in the EE server. 
Either rewrite them as web components, or, provide an alternate (non-JTA) persistence unit 
in persistence.xml and see if they still work. Or, just delete them and use psql, 
as in the Verify section above.
